### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by qaidjoharj53** [mdnazisharman2803/dartified#1]
Can you please just give me a hint that what this project is about?

**Comment by mdnazisharman2803** [comment]
> Can you please just give me a hint that what this project is about?

It is smart app project where you can feed your documents, and get answers from your documents using LLM

**Comment by mdnazisharman2803** [comment]
I'd say... Let's not update readme for now because we need a backend structure first and then we have to add installation steps accordingly.. You can work on contributing guidelines
