### ISSUE TITLE
feat: Add React Template for `dartified`

### ISSUE THREAD

**Issue by Abhishek-Mallick** [mdnazisharman2803/dartified#4]
I want to create a starter template for `dartified` on React

> smart app project where you can feed your documents, and get answers from your documents using LLM

It would be easier if it is later incorporated with `Reactpy` a new Python library to integrate python with React
We can use `.bin` or `.pkl` for storing the saved state of LLM model

This will help people have a template in which they want to contribute to and bring up new ideas.

Please assign this to me under hacktoberfest

**Comment by mdnazisharman2803** [comment]
its not react project
