### ISSUE TITLE
feat : Update Readme.md

### ISSUE THREAD

**Issue by Abhishek-Mallick** [mdnazisharman2803/dartified#5]
The Readme needs to be updated
- Details about the project
- Installation procedure
- Steps to contribute further
- Steps designing the LLM model

**Comment by MaryamMansour** [comment]
can i work on it? I'll update it as much as possible .. assign me

**Comment by mdnazisharman2803** [comment]
@MaryamMansour  please go ahead

**Comment by ayushsgit** [comment]
Once the assignee is done with the task let me know , I will see if further changes are required to make it look better

**Comment by alamdilshad87** [comment]
Hello There,
Can you assign me this. And mark this hacktober accepted as this can be my first PR for Hacktoberfest
